language: node_js

node_js:
  7

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run lint
  - npm test
  - npm run build

deploy:
  - provider: npm
    email: eziosyanse@gmail.com
    api_key: $npm_token
    skip_cleanup: true
    on:
      tags: true
